'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Prerequisite
    Public Property course_id As Integer
    Public Property prerequisite_course_id As Nullable(Of Integer)
    Public Property languageID As Nullable(Of Integer)

End Class
